language: node_js
node_js:
  - "12"

jobs:
  include:
    - stage: Testing
      script:
        - npm i
        - npm run test:unit || travis_terminate 1
    - stage: Publish in npm
      if: tag =~ ^v
      script:
        - npm i && npm run build
        - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish
